name: Acceptance tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use task
        uses: arduino/setup-task@v2

      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Run the client unit tests
        run: task test
