version: 3
tasks:
  install: yarn install
  test:
    - task: install
    - yarn vitest --run
  bundle:
    - task: install
    - yarn ng build
  start:
    - task: bundle
    - yarn ng serve --port 8080
